### PR TITLE
Failed attempt

### PR DESCRIPTION
**Pull request by Sofistication**
- wasn't sure where to start with each

I plan to attempt this again if we have workshop time later

### CODE REVIEW

**Comment by bernardlee** [comment]
Did you run bundle install?  The tests for this challenge requires a gem called "binding_of_caller".

**Comment by Sofistication** [comment]
I don't know where that link to an issue came from, I meant to say I didn't know where to start with each

**Comment by bernardlee** [comment]
`#each` needs to `yield` to a block.

**Comment by Sofistication** [comment]
I had a look at the solution branch and my approach was very wrong, or at least very different. I'm going to attempt it again later (without looking back to the solution branch, but basing off memory).

**Comment by bernardlee** [comment]
The solution branch was just updated.

**Pull request closed without merging**
